version: '3'

services:
 solr:
  image: "solr:latest"
  entrypoint:
   - docker-entrypoint.sh
   - solr-precreate
   - newsitem
  ports:
   - "8983"

 web:
  build: .
  ports:
    - "8080:8080"
  depends_on:
   - solr


